<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

**Exercise 1 (Total recall)** 

Purely from memory, write short descriptions of the following terms:

| **Term**  | **Brief description**  |
|---|---|
|  Subsetting | Carving of some data from a list or array to be put in a separate data.  |
|  Indexing | Calling out needed data through their index.  |
|  Slicing | Subsetting of an existing list or array using a range  |
| Masking  | Subsetting by using True/False  |






| **Term**  | **Brief description**  |
|---|---|
|  Subsetting | *Subsetting is to select a subset of data in a list, it is more of a generic term compared to slicing or indexing.*   |
|  Indexing | *It is selecting one element from a list or array, like calling out.*  |
|  Slicing | *Selecting a range of elements from a list/array.* |
| Masking  | *Asking a question to an array, and through its True/False answer, subsetting the desired data into another array.* |

**Exercise 2 (Show me the 'odd' letters)** 

Use masking to subset the letters that correspond to the odd numbers. I.e., get the result [A, C, E, G, I].

This is a slightly tricky problem because arrays are fussy about type. So, let me give you a recipe to solve this problem.

1. Subset all the first elements.
You should get array(['1', '3', '2', ..., '10', '9'])
2. Convert this to integers using astype(int)
You must look up how astype() works.
3. Use % to get the remainder for division by 2.
You should get array([1, 1, 0, ..., 0, 1]).
4. Use the previous result to create a mask that checks if the remainder is zero or not
You should get array([True, True, False, ..., False, True]).
Now you have identified the locations of the odd numbers.
5. Use the mask and extract the corresponding second elements.

In [7]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [23]:
numbers = np_array_2d[:,0]

In [26]:
numbers2 = numbers.astype(int, copy=True)

In [35]:
rem = numbers2%2
print(rem)

[1 1 0 0 1 1 0 0 0 1]


In [42]:
my_mask = (rem == 1)
subset = np_array_2d[my_mask]
subset[:,1]

array(['A', 'C', 'E', 'G', 'I'], dtype='<U21')

**Exercise 3** 

Consider the 2D array shown above. Using your knowledge of NumPy masking, change:

values below 50 to -1,
values above 50 to +1, and
values equal to 50 to 0.
You should end up with:

[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


In [ ]:
list = [[66, 50, 57, -1, -1],
 [92, -1, 88, -1, -1],
 [75, -1, -1, 76, -1],
 [-1, 51, 87, -1, -1],
 [71, -1, 67, -1, 69]]


array = np.array(list)
array[(array<50)]





array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1])