<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

In [4]:
import numpy as np

# What to expect in this chapter

# 1 Subsetting: Indexing and Slicing

## 1.1 Lists & Arrays in 1D | Subsetting & Indexing

In [5]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array = np.array(py_list)

# Pick one
x = py_list  # OR
x = np_array

In [14]:
py_list[2:7]

['c3', 'd4', 'e5', 'f6', 'g7']

In [ ]:
py_list[0:7:2]

py_list[5:2:-1] #reverse the order

#if you add another colon, it will cause it to display every element until the max (7) in steps of two

['f6', 'e5', 'd4']

In [19]:
py_list[:5]

['a1', 'b2', 'c3', 'd4', 'e5']

## 1.2 Arrays only | Subsetting by masking

In [31]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array % 3 ==0
np_array[my_mask]

#if you sum this, it is the sum of the numbers that meet your conditions

np_array[my_mask].sum()


np.int64(18)

In [ ]:
my_mask.sum()

#how to count how many values meet your criteria

np.int64(3)

In [25]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [26]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [37]:
np_array[(np_array >3) & (np_array<8)]

array([4, 5, 6, 7])

In [47]:
np_array(np_array >3).logical_and(np_array<8)

#huhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh

TypeError: 'numpy.ndarray' object is not callable

## 1.3 Lists & Arrays in 2D | Indexing & Slicing

## 1.4 Growing lists

In [48]:
x=[1, 2]*5
x

[1, 2, 1, 2, 1, 2, 1, 2, 1, 2]

In [ ]:
x=[1]
x= x + [2]
x= x + [3]
x= x + [4]
x
x=[1]
x+= [2]
x+= [3]
x+= [4]
x
x=[1]
x.append(2)
x.append(3)
x.append(4)
x


#different ways of extendong a list

[1, 2, 3, 4]

In [50]:
x = [1, 2, 3]
x += [4, 5, 6]
x
x=[1, 2, 3]
x.extend([4, 5, 6])
x
x=[1, 2, 3]
x.append([4, 5, 6])
x

[1, 2, 3, [4, 5, 6]]

# Some loose ends

## 1.5 Tuples

In [53]:
a = (1,2,3)  #tuple
b = [1,2,3]   #list

In [54]:
a + [1] 

TypeError: can only concatenate tuple (not "list") to tuple

In [55]:
b + [1]

[1, 2, 3, 1]

## 1.6 Be VERY careful when copying

In [57]:
x=[1, 2, 3]
y=x           # DON'T do this!
z=x           # DON'T do this!


print(f'{x=}', f'{y=}', f'{z=}')



x=[1, 2, 3] y=[1, 2, 3] z=[1, 2, 3]


In [59]:
x.append(1)
z.append(1000)
print(f'{x=}', f'{y=}', f'{z=}')  

#careful so that you dont link everything

x=[1, 2, 3, 1, 1000, 1, 1000] y=[1, 2, 3, 1, 1000, 1, 1000] z=[1, 2, 3, 1, 1000, 1, 1000]


In [60]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Footnotes