<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

# What to expect in this chapter

In [8]:
import numpy as np

# 1 Lists, Arrays & Dictionaries

**Python Lists**
1. py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]
2. py_real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

In [9]:
np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])
np_real_names = np.array(["Natasha Romanoff", "Tony Stark", "Stephen Strange"])

In [1]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}

## 1.1 Let’s compare

## 1.2 Accessing data from a list (or array)

In [16]:
i=1
print(np_real_names[i], "is", np_super_names[i])

Tony Stark is Iron Man


In [12]:
i=-1
print(np_real_names[i])

Stephen Strange


## 1.3 Accessing data from a dictionary

In [18]:
superhero_info = {
    "Natasha Romanoff": "Black Widow",
    "Tony Stark": "Iron Man",
    "Stephen Strange": "Doctor Strange"
}                  

superhero_info["Peter Parker"] = "Spiderman" 

print(superhero_info)

{'Natasha Romanoff': 'Black Widow', 'Tony Stark': 'Iron Man', 'Stephen Strange': 'Doctor Strange', 'Peter Parker': 'Spiderman'}


In [21]:
superhero_info.keys()

# when you want to access disctionary, you put words in the [] rather than numbers

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange', 'Peter Parker'])

In [22]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange', 'Spiderman'])

## 1.4 Higher dimensional lists

In [19]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

py_superhero_info[-1][-1]

'Doctor Strange'

# 2 Lists vs. Arrays

## 2.1 Size

usually convert a list into a numpy list?

numpy lists are usually more neat, they will convert all the values into the smae type of data 
eg numbers to strings
but if you want to add the numbers-turned strings together then you start to have a problem

In [ ]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)      # Reusing the Python list 
                                        # to create a NEW
                                        # NumPy array


(10, 2)

In [26]:
print(np_array_2d)

[['1' 'A']
 ['2' 'B']
 ['3' 'C']
 ['4' 'D']
 ['5' 'E']
 ['6' 'F']
 ['7' 'G']
 ['8' 'H']
 ['9' 'I']
 ['10' 'J']]


In [29]:
len(py_list_2d)

10

In [28]:
len(np_array_2d)

10

In [27]:
np_array_2d.shape

(10, 2)

## 2.2 Arrays are fussy about type

numpy is very fussy about the number of elements per row because they are very optimised for adding number together 

## 2.3 Adding a number

In [30]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         # Reusing the Python list
                                     # to create a NEW
                                     # NumPy array

In [ ]:
np_array + 10

array([11, 12, 13, 14, 15])

In [32]:
py_list + 10        # Won't work!

TypeError: can only concatenate list (not "int") to list

## 2.4 Adding another list

In [33]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [34]:
py_list_1 + py_list_2
np_array_1 + np_array_2

array([11, 22, 33, 44, 55])

## 2.5 Multiplying by a Number

numpy likes to work with the elements, they will add the ekements inside together
while for lists, they will literally just try to combine the two lists togther 
even for multiplying them both by two:

(aka arrays are better with numbers, better to convert)

In [35]:
py_list*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [36]:
np_array_1*3

array([ 3,  6,  9, 12, 15])

## 2.6 Squaring

In [37]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [56]:
print("**Lists**")

py_list = [1,2,3,4,5]
np_list = np.array(py_list)
py_list >3

**Lists**


TypeError: '>' not supported between instances of 'list' and 'int'

In [57]:
np_list >3

array([False, False, False,  True,  True])

In [54]:
##very important concept for many many data sets

mask = np_array >3

np_array[mask].sum()

np.int64(9)

In [50]:
(np_array > 3).sum()

np.int64(2)

## 2.7 Asking questions

## 2.8 Mathematics

In [ ]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)         

In [58]:
sum(py_list)     # sum() is a base Python function
max(py_list)     # max() is a base Python function
min(py_list)     # min() is a base Python function
np_array.sum()
np_array.max()
np_array.min()
np_array.mean()
np_array.std()

np.float64(1.4142135623730951)

## Footnotes